### ISSUE TITLE
The last code doesn't run

### ISSUE THREAD

**Issue by mdtrooper** [obozrenie/obozrenie#3]
Hi.

The last code doesn't run.

This is the output:

```
miguel@miguel-HP-Pavilion-dm4-Notebook-PC /tmp/obozrenie $ ./obozrenie-gtk 
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/obozrenie/obozrenie/launch_gtk.py", line 23, in <module>
    from obozrenie.gtk import *
  File "/tmp/obozrenie/obozrenie/gtk.py", line 32, in <module>
    import obozrenie.helpers as helpers
  File "/tmp/obozrenie/obozrenie/helpers.py", line 86
    print(" | ".join([time.strftime('%F %T'), *[str(part) for part in msg]]))
                                                     ^
SyntaxError: can use starred expression only as assignment target
miguel@miguel-HP-Pavilion-dm4-Notebook-PC /tmp/obozrenie $ git log --format="%H" -n 1
e3861f395f8538810e54082591b98e762873e6e9

```

Thanks, regards.

**Comment by mdtrooper** [comment]
Hi again.

There is same bug in the last release https://github.com/obozrenie/obozrenie/releases/tag/1 .

Sorry.

**Comment by vorot93** [comment]
Thanks for the report. The latest git master rev should be working for you.
